#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

wmake $makeType ./thermophysicalModels/basic
wmake $makeType ./thermophysicalModels/reactionThermo

wmake $makeType ./turbulenceModels/compressible/turbulenceModel
wmake $makeType ./turbulenceModels/compressible/RAS
wmake $makeType ./turbulenceModels/compressible/LES

wmake $makeType ./combustionModels

# ----------------------------------------------------------------- end-of-file
